"""
LifeOS Backend — Secure Sharing Router
Endpoints for generating and fetching temporary shared links for medical profiles.
"""

import logging
from datetime import datetime, timedelta, timezone
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy.orm import selectinload

from app.database import get_db
from app.routers.auth import get_current_user
from app.models.user import User, UserProfile
from app.models.emergency import EmergencyContact
from app.models.share import SharedLink
from app.models.medical_record import MedicalRecord
from app.models.family import Vaccination
from app.schemas.user import UserProfileResponse

logger = logging.getLogger("lifeos.share")

router = APIRouter(prefix="/share", tags=["Share"])

@router.post("/generate")
async def generate_shared_link(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Generate a secure sharing link token that expires in 24 hours.
    Deletes any previously generated active tokens for this user to ensure only one is active at a time.
    """
    try:
        # Delete old tokens
        result = await db.execute(select(SharedLink).where(SharedLink.user_id == current_user.id))
        old_links = result.scalars().all()
        for link in old_links:
            await db.delete(link)
        
        # Create new token (UUID is auto-generated by the model)
        new_link = SharedLink(
            user_id=current_user.id,
            expires_at=datetime.utcnow() + timedelta(hours=24)
        )
        db.add(new_link)
        await db.commit()
        await db.refresh(new_link)
        
        return {"token": new_link.token, "expires_at": new_link.expires_at}
    except Exception as e:
        logger.error(f"Error generating shared link: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate secure link"
        )

@router.get("/{token}")
async def get_shared_profile(
    token: str,
    db: AsyncSession = Depends(get_db)
):
    """
    Public endpoint. Validates token and returns the medical profile.
    Requires no auth, but fails if token is invalid or expired.
    """
    result = await db.execute(select(SharedLink).where(SharedLink.token == token))
    link = result.scalar_one_or_none()
    
    if not link:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Link not found or invalid")
        
    if datetime.utcnow() > link.expires_at:
        await db.delete(link)
        await db.commit()
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="This secure link has expired")
        
    # Fetch the profile
    profile_result = await db.execute(
        select(UserProfile).where(UserProfile.user_id == link.user_id)
    )
    profile = profile_result.scalar_one_or_none()
    
    if not profile:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Profile not found")
        
    # Fetch recent medical records
    records_result = await db.execute(
        select(MedicalRecord).where(MedicalRecord.user_id == link.user_id).order_by(MedicalRecord.date.desc()).limit(10)
    )
    records = records_result.scalars().all()
    
    # Fetch vaccinations
    vax_result = await db.execute(
        select(Vaccination).where(Vaccination.user_id == link.user_id).order_by(Vaccination.date.desc())
    )
    vaccinations = vax_result.scalars().all()

    # Fetch emergency contacts
    contacts_result = await db.execute(
        select(EmergencyContact).where(EmergencyContact.user_id == link.user_id)
    )
    contacts = contacts_result.scalars().all()

    return {
        "profile": {
            "name": profile.name,
            "age": profile.age,
            "gender": profile.gender,
            "blood_type": profile.blood_type,
            "height": profile.height,
            "weight": profile.weight,
            "allergies": profile.allergies,
            "conditions": profile.conditions,
            "organ_donor": profile.organ_donor
        },
        "contacts": [
            {"name": c.name, "phone": c.phone, "relation": c.relation}
            for c in contacts
        ],
        "records": [
            {
                "id": r.id,
                "title": r.title,
                "category": r.category,
                "date": r.date.isoformat() if hasattr(r.date, "isoformat") else str(r.date),
                "doctor": r.doctor,
                "hospital": r.hospital,
                "findings": r.findings
            }
            for r in records
        ],
        "vaccinations": [
            {
                "id": v.id,
                "name": v.name,
                "date": v.date.isoformat() if hasattr(v.date, "isoformat") else str(v.date),
                "status": v.status,
                "person": v.person
            }
            for v in vaccinations
        ]
    }
